/* Iteris Code — уроки. Кожен урок: t (назва), p (абзаци), code (блоки коду), note (важливе), tasks (завдання) */
const LESSONS = {
python: [
{ t: "Перша програма: print і коментарі",
  p: ["Python читає програму зверху вниз і виконує кожен рядок по черзі. Найпростіша дія — вивести текст на екран функцією <code>print()</code>.", "Усе, що йде після знака <code>#</code>, Python ігнорує. Так у код додають пояснення для людей."],
  code: ['print("Привіт, світе!")\n# це коментар, його не видно у виводі\nprint(2 + 3)\nprint("2 + 3 =", 2 + 3)'],
  note: "Текст завжди беруть у лапки, а вирази без лапок обчислюються: <code>print(2 + 3)</code> виведе 5.",
  tasks: ["Виведіть своє ім'я та місто двома окремими print.", "Виведіть результат виразу 15 * 4 - 7."] },
{ t: "Змінні та типи даних",
  p: ["Змінна — це ім'я, під яким у пам'яті зберігається значення. Її створюють знаком <code>=</code>, окрема команда оголошення не потрібна.", "Основні типи: <code>int</code> (ціле), <code>float</code> (дробове), <code>str</code> (рядок) і <code>bool</code> (True або False). Дізнатися тип можна функцією <code>type()</code>."],
  code: ['age = 16\nheight = 1.75\nname = "Олена"\nis_student = True\n\nprint(name, age, height, is_student)\nprint(type(age), type(height), type(name))\n\nage = age + 1\nprint("Наступного року:", age)'],
  note: "Імена змінних не можуть починатися з цифри й не містять пробілів. Python розрізняє <code>age</code> і <code>Age</code>.",
  tasks: ["Збережіть у змінних свою вагу та зріст і виведіть їх.", "Перевірте type() для значень 7, 7.0 і \"7\"."] },
{ t: "Ввід даних і розгалуження",
  p: ["Функція <code>input()</code> зупиняє програму й чекає, поки користувач щось введе. Результат завжди рядок, тому для чисел його перетворюють через <code>int()</code> або <code>float()</code>.", "Конструкція <code>if / elif / else</code> дозволяє вибрати одну з гілок. Тіло гілки позначають відступом у чотири пробіли."],
  code: ['age = int(input("Скільки вам років? "))\n\nif age < 12:\n    print("Дитячий квиток")\nelif age < 18:\n    print("Підлітковий квиток")\nelse:\n    print("Дорослий квиток")'],
  note: "Порівняння записують так: <code>==</code> дорівнює, <code>!=</code> не дорівнює, <code>&lt;=</code> і <code>&gt;=</code> нестрогі нерівності.",
  tasks: ["Напишіть програму, що визначає, парне число чи непарне (підказка: <code>n % 2</code>).", "Додайте до квитків окрему гілку для віку від 65 років."] },
{ t: "Цикли for і while",
  p: ["Цикл повторює блок коду. <code>for</code> зручний, коли відомо, скільки разів повторювати, а <code>while</code> працює, поки умова істинна.", "Функція <code>range(a, b)</code> дає числа від a до b-1. Якщо умова у while ніколи не стане хибною, цикл не закінчиться."],
  code: ['for i in range(1, 6):\n    print("Крок", i)\n\nsum_ = 0\nn = 1\nwhile n <= 100:\n    sum_ += n\n    n += 1\nprint("Сума від 1 до 100:", sum_)'],
  note: "Запис <code>x += 1</code> — це скорочення від <code>x = x + 1</code>.",
  tasks: ["Виведіть таблицю множення на 7 від 1 до 10.", "За допомогою while знайдіть, скільки разів число 1000 ділиться на 2 націло."] }
],
cpp: [
{ t: "Перша програма на C++",
  p: ["C++ — компільована мова: спочатку код перетворюється на виконуваний файл, потім запускається. Кожна програма починається з функції <code>main</code>.", "Рядок <code>#include &lt;iostream&gt;</code> підключає бібліотеку вводу-виводу, а <code>cout</code> виводить дані в консоль."],
  code: ['#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Привіт, світе!" << endl;\n    cout << "2 + 3 = " << 2 + 3 << endl;\n    return 0;\n}'],
  note: "Кожна інструкція завершується крапкою з комою. Її відсутність — найчастіша помилка новачків.",
  tasks: ["Виведіть три рядки: ім'я, клас, улюблений предмет.", "Виведіть результат виразу (8 + 4) * 3."] },
{ t: "Змінні, типи та ввід",
  p: ["У C++ тип змінної потрібно вказати під час оголошення: <code>int</code> для цілих, <code>double</code> для дробових, <code>char</code> для символу, <code>string</code> для тексту.", "Читати значення з клавіатури допомагає <code>cin</code>."],
  code: ['#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    string name;\n    int age;\n    cout << "Ім\'я: ";\n    cin >> name;\n    cout << "Вік: ";\n    cin >> age;\n    cout << name << ", через 5 років вам буде " << age + 5 << endl;\n    return 0;\n}'],
  note: "Ділення цілих чисел відкидає дробову частину: <code>7 / 2</code> дає 3, а <code>7 / 2.0</code> дає 3.5.",
  tasks: ["Прочитайте два числа й виведіть їхню суму та добуток.", "Обчисліть площу кола за радіусом (число пі візьміть як 3.14)."] },
{ t: "Умови та цикли",
  p: ["Умовний оператор <code>if</code> працює так само, як у інших мовах, а тіло гілки береться у фігурні дужки.", "Для повторень є <code>for</code> з трьома частинами (початок, умова, крок) і <code>while</code>."],
  code: ['#include <iostream>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    if (n % 2 == 0) {\n        cout << "Парне" << endl;\n    } else {\n        cout << "Непарне" << endl;\n    }\n    for (int i = 1; i <= n; i++) {\n        cout << i << " ";\n    }\n    cout << endl;\n    return 0;\n}'],
  note: "Один знак <code>=</code> присвоює значення, два знаки <code>==</code> порівнюють.",
  tasks: ["Виведіть усі парні числа від 1 до n.", "Підрахуйте суму цифр числа за допомогою while (підказка: <code>% 10</code> і <code>/ 10</code>)."] }
],
pascal: [
{ t: "Структура програми на Pascal",
  p: ["Програма на Pascal має чітку структуру: заголовок, розділ опису змінних і головний блок між <code>begin</code> та <code>end.</code>.", "Для виведення тексту є процедури <code>write</code> (без переходу на новий рядок) і <code>writeln</code> (з переходом)."],
  code: ["program Hello;\nbegin\n  writeln('Привіт, світе!');\n  write('2 + 3 = ');\n  writeln(2 + 3);\nend."],
  note: "Після останнього <code>end</code> стоїть крапка, а не крапка з комою.",
  tasks: ["Виведіть назву своєї школи у три рядки.", "Виведіть результат виразу 10 div 3 та 10 mod 3."] },
{ t: "Змінні та ввід-вивід",
  p: ["Змінні в Pascal описують у розділі <code>var</code> до початку програми. Основні типи: <code>integer</code>, <code>real</code>, <code>string</code>, <code>boolean</code>.", "Присвоювання записують як <code>:=</code>, а вводять дані процедурою <code>readln</code>."],
  code: ["var\n  a, b: integer;\n  s: real;\nbegin\n  write('Введіть два числа: ');\n  readln(a, b);\n  s := (a + b) / 2;\n  writeln('Середнє: ', s:0:2);\nend."],
  note: "Запис <code>s:0:2</code> задає формат: два знаки після коми.",
  tasks: ["Обчисліть периметр і площу прямокутника за двома сторонами.", "Поміняйте місцями значення двох змінних через третю."] },
{ t: "Умовний оператор і цикл for",
  p: ["Умовний оператор має вигляд <code>if ... then ... else</code>. Перед <code>else</code> крапка з комою не ставиться.", "Цикл <code>for i := 1 to n do</code> повторює дію відому кількість разів. Якщо дій кілька, їх беруть у <code>begin ... end</code>."],
  code: ["var\n  n, i, sum: integer;\nbegin\n  readln(n);\n  if n > 0 then\n    writeln('Додатне')\n  else\n    writeln('Не додатне');\n  sum := 0;\n  for i := 1 to n do\n    sum := sum + i;\n  writeln('Сума 1..n = ', sum);\nend."],
  note: "Для спадного циклу використовують <code>downto</code> замість <code>to</code>.",
  tasks: ["Виведіть квадрати чисел від 1 до 10.", "Визначте більше з двох введених чисел."] }
],
html: [
{ t: "Структура HTML-документа",
  p: ["HTML описує зміст сторінки за допомогою тегів. Більшість тегів парні: відкривальний <code>&lt;p&gt;</code> і закривальний <code>&lt;/p&gt;</code>.", "Кожна сторінка має однакову основу: <code>head</code> містить службову інформацію, а <code>body</code> те, що бачить користувач."],
  code: ['<!DOCTYPE html>\n<html lang="uk">\n<head>\n  <meta charset="utf-8">\n  <title>Мій перший сайт</title>\n</head>\n<body>\n  <h1>Привіт, світе!</h1>\n  <p>Це мій перший абзац.</p>\n</body>\n</html>'],
  note: "Без <code>&lt;meta charset=\"utf-8\"&gt;</code> українські літери можуть відображатися некоректно.",
  tasks: ["Створіть сторінку з вашим іменем у заголовку та двома абзацами.", "Змініть заголовок вкладки браузера через тег title."] },
{ t: "Заголовки, списки та посилання",
  p: ["Заголовки <code>h1</code>–<code>h6</code> задають структуру тексту: h1 один на сторінку, далі за рівнями. Маркований список — <code>ul</code>, нумерований — <code>ol</code>, а кожен пункт — <code>li</code>.", "Посилання створює тег <code>a</code> з атрибутом <code>href</code>, а картинку — <code>img</code> з атрибутами <code>src</code> і <code>alt</code>."],
  code: ['<h2>Мої хобі</h2>\n<ul>\n  <li>Програмування</li>\n  <li>Футбол</li>\n</ul>\n\n<ol>\n  <li>Прокинутись</li>\n  <li>Написати код</li>\n</ol>\n\n<a href="https://developer.mozilla.org" target="_blank">Довідник MDN</a>'],
  note: "Атрибут <code>alt</code> у зображення обов'язковий: його читають програми екранного доступу.",
  tasks: ["Зробіть нумерований список зі своїх п'яти планів на тиждень.", "Додайте посилання на улюблений сайт, що відкривається в новій вкладці."] },
{ t: "Таблиці та форми",
  p: ["Таблицю будують із рядків <code>tr</code>, у яких стоять комірки <code>td</code> або заголовкові <code>th</code>.", "Форма збирає дані користувача. Кожне поле — це <code>input</code> із типом (<code>text</code>, <code>email</code>, <code>number</code>), а підпис прив'язується тегом <code>label</code>."],
  code: ['<table border="1">\n  <tr><th>Мова</th><th>Рік</th></tr>\n  <tr><td>Python</td><td>1991</td></tr>\n  <tr><td>JavaScript</td><td>1995</td></tr>\n</table>\n\n<form>\n  <label for="n">Ім\'я</label>\n  <input id="n" type="text" required>\n  <button type="submit">Надіслати</button>\n</form>'],
  note: "Зв'язок <code>label for</code> і <code>id</code> дає клік по підпису для фокусу на полі.",
  tasks: ["Створіть таблицю розкладу з трьох уроків.", "Додайте форму реєстрації з полями імені, пошти та віку."] }
],
css: [
{ t: "Підключення CSS і селектори",
  p: ["CSS описує зовнішній вигляд HTML-елементів. Правило складається з селектора та блоку властивостей у фігурних дужках.", "Селектор може бути за тегом (<code>p</code>), класом (<code>.card</code>) або id (<code>#main</code>). Файл стилів підключають у head."],
  code: ['<link rel="stylesheet" href="style.css">\n\n/* style.css */\nbody {\n  font-family: Arial, sans-serif;\n}\nh1 {\n  color: #2F5BEA;\n}\n.card {\n  background: #f4f6ff;\n  border-radius: 8px;\n}\n#main {\n  max-width: 600px;\n}'],
  note: "Клас можна застосувати до багатьох елементів, а id має бути унікальним на сторінці.",
  tasks: ["Змініть колір і розмір шрифту для всіх абзаців.", "Створіть клас <code>.warn</code> із червоним текстом і застосуйте його до одного елемента."] },
{ t: "Блочна модель",
  p: ["Кожен елемент — це прямокутна коробка з чотирьох шарів: вміст, внутрішній відступ (<code>padding</code>), рамка (<code>border</code>) і зовнішній відступ (<code>margin</code>).", "Властивість <code>box-sizing: border-box</code> змушує width враховувати padding і рамку, тому розміри стають передбачуваними."],
  code: ['* {\n  box-sizing: border-box;\n}\n.box {\n  width: 300px;\n  padding: 20px;\n  border: 2px solid #14213D;\n  margin: 16px auto;\n}'],
  note: "Значення <code>margin: 16px auto</code> центрує блок по горизонталі, якщо задана ширина.",
  tasks: ["Зробіть блок шириною 400px із рамкою й відступами та відцентруйте його.", "Поекспериментуйте: як зміниться розмір, якщо прибрати box-sizing?"] },
{ t: "Flexbox: розташування елементів",
  p: ["Flexbox вишиковує дочірні елементи в рядок або стовпчик. Достатньо задати батьківському елементу <code>display: flex</code>.", "Вирівнювання вздовж головної осі відповідає за <code>justify-content</code>, а впоперек — <code>align-items</code>. Властивість <code>gap</code> задає проміжок між елементами."],
  code: ['.menu {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 12px;\n  flex-wrap: wrap;\n}\n.menu a {\n  flex: 1 1 120px;\n}'],
  note: "Щоб елементи йшли стовпчиком, додайте <code>flex-direction: column</code>.",
  tasks: ["Зробіть горизонтальне меню з чотирьох посилань.", "Розташуйте три картки в ряд, щоб на вузькому екрані вони переносились."] }
],
js: [
{ t: "Змінні та типи в JavaScript",
  p: ["JavaScript працює у браузері й оживляє сторінки. Змінні оголошують словами <code>let</code> (значення можна змінювати) та <code>const</code> (не можна).", "Основні типи: число, рядок, булеве значення, <code>null</code> і <code>undefined</code>. Вивід у консоль робить <code>console.log()</code>."],
  code: ['let age = 16;\nconst name = "Олена";\nconst isStudent = true;\n\nage = age + 1;\nconsole.log(name + " має " + age + " років");\nconsole.log(typeof age, typeof name, typeof isStudent);\nconsole.log(10 / 4, 10 % 4);'],
  note: "Для порівняння використовуйте <code>===</code>, а не <code>==</code>: він не змінює типи неявно.",
  tasks: ["Обчисліть площу трикутника за основою й висотою та виведіть у консоль.", "З'ясуйте, що виведе typeof для масиву [1, 2]."] },
{ t: "Функції",
  p: ["Функція — це іменований блок коду, який можна викликати багато разів. Вона приймає параметри й повертає результат через <code>return</code>.", "Крім класичного запису існує коротка стрілкова функція <code>(a, b) =&gt; a + b</code>."],
  code: ['function square(x) {\n  return x * x;\n}\n\nconst add = (a, b) => a + b;\n\nconsole.log(square(5));\nconsole.log(add(2, 3));\nconsole.log(square(add(1, 2)));'],
  note: "Функція без <code>return</code> повертає <code>undefined</code>.",
  tasks: ["Напишіть функцію max(a, b), що повертає більше число.", "Створіть стрілкову функцію, що перетворює градуси Цельсія на Фаренгейти (C × 9/5 + 32)."] },
{ t: "Масиви та цикли",
  p: ["Масив зберігає впорядкований набір значень. Індексація починається з нуля, а довжина доступна у <code>length</code>.", "Перебрати масив допомагає цикл <code>for...of</code>, а перетворити його — методи <code>map</code> і <code>filter</code>."],
  code: ['const nums = [3, 8, 1, 6];\nnums.push(10);\n\nfor (const n of nums) {\n  console.log(n);\n}\n\nconst doubled = nums.map(n => n * 2);\nconst big = nums.filter(n => n > 5);\nconsole.log(doubled, big, nums.length);'],
  note: "Методи <code>map</code> і <code>filter</code> не змінюють початковий масив, а повертають новий.",
  tasks: ["Порахуйте суму всіх елементів масиву циклом.", "Відфільтруйте з масиву лише парні числа."] },
{ t: "DOM і події",
  p: ["DOM — це дерево елементів сторінки, яким керує JavaScript. Знайти елемент можна через <code>document.querySelector</code>, а змінити текст — через <code>textContent</code>.", "Реакцію на дії користувача задає метод <code>addEventListener</code>."],
  code: ['<button id="btn">Натисни</button>\n<p id="out">0</p>\n\n<script>\n  let count = 0;\n  const btn = document.querySelector("#btn");\n  const out = document.querySelector("#out");\n  btn.addEventListener("click", () => {\n    count++;\n    out.textContent = count;\n  });\n</script>'],
  note: "Скрипт, що шукає елементи, розміщують після них у HTML або запускають після події <code>DOMContentLoaded</code>.",
  tasks: ["Зробіть кнопку, що змінює колір фону сторінки.", "Додайте другу кнопку, що скидає лічильник."] }
],
sql: [
{ t: "Вибірка даних: SELECT",
  p: ["SQL — мова запитів до реляційних баз даних. Дані лежать у таблицях зі стовпчиками та рядками, а запит <code>SELECT</code> вибирає потрібні стовпчики.", "Зірочка <code>*</code> означає всі стовпчики, а <code>DISTINCT</code> прибирає дублікати."],
  code: ['SELECT * FROM students;\n\nSELECT name, grade FROM students;\n\nSELECT DISTINCT city FROM students;'],
  note: "Ключові слова SQL не залежать від регістру, але їх прийнято писати великими літерами.",
  tasks: ["Виберіть лише імена та міста всіх учнів.", "Отримайте список унікальних класів."] },
{ t: "Фільтрація й сортування",
  p: ["Умову відбору задають у <code>WHERE</code> за допомогою порівнянь, <code>AND</code>, <code>OR</code>, <code>IN</code> і <code>LIKE</code>. Порядок рядків визначає <code>ORDER BY</code>.", "Обмежити кількість рядків можна ключовим словом <code>LIMIT</code>."],
  code: ["SELECT name, grade\nFROM students\nWHERE grade >= 10 AND city = 'Дніпро'\nORDER BY grade DESC, name ASC\nLIMIT 5;\n\nSELECT * FROM students\nWHERE name LIKE 'О%';"],
  note: "Текст у SQL беруть в одинарні лапки. Символ <code>%</code> у LIKE замінює будь-яку кількість літер.",
  tasks: ["Виберіть трьох учнів із найвищими оцінками.", "Знайдіть усіх, чиє ім'я закінчується на «а»."] },
{ t: "Групування та JOIN",
  p: ["Функції <code>COUNT</code>, <code>SUM</code>, <code>AVG</code>, <code>MIN</code>, <code>MAX</code> рахують підсумки. Разом з <code>GROUP BY</code> вони дають статистику по групах.", "Оператор <code>JOIN</code> об'єднує дві таблиці за спільним стовпчиком, наприклад за ідентифікатором."],
  code: ['SELECT city, COUNT(*) AS total, AVG(grade) AS avg_grade\nFROM students\nGROUP BY city;\n\nSELECT s.name, c.title\nFROM students s\nJOIN courses c ON c.id = s.course_id;'],
  note: "Умову на результат групування пишуть у <code>HAVING</code>, а не у WHERE.",
  tasks: ["Порахуйте, скільки учнів у кожному класі.", "Виведіть імена учнів разом із назвою курсу через JOIN."] }
]
};
